name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: go HW8 -v ./...
      run: go test_8.1 -v ./...
